# Generated by Django 4.0.6 on 2025-04-13 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('module', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sys_content_type',
                'ordering': ['id'],
                'managed': True,
                'unique_together': {('app_label', 'module')},
            },
        ),
        migrations.CreateModel(
            name='SysMenu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('menu_name_cn', models.CharField(max_length=255)),
                ('menu_name_en', models.CharField(max_length=255)),
                ('seq_no', models.IntegerField()),
                ('menu_icon', models.TextField(blank=True, null=True)),
                ('menu_type', models.CharField(max_length=255)),
                ('menu_route', models.CharField(max_length=255)),
                ('par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='system.sysmenu')),
            ],
            options={
                'db_table': 'sys_menu',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SysPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('route', models.CharField(max_length=255, unique=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='system.syscontenttype')),
                ('par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='system.syspermission')),
            ],
            options={
                'db_table': 'sys_permission',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SysRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('status', models.IntegerField()),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sys_role',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'sys_user',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SysUserRoles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='system.sysrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='system.sysuser')),
            ],
            options={
                'db_table': 'sys_user_roles',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SysRolePermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='system.syspermission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='system.sysrole')),
            ],
            options={
                'db_table': 'sys_role_permissions',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SysRoleMenu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='system.sysmenu')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='system.sysrole')),
            ],
            options={
                'db_table': 'sys_role_menu',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
